name: Build Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    env:
      RAT_URL: "https://rascalsoftware.github.io/RAT-Docs/"
      RAT_VERSION: "dev"
    runs-on: Linux

    steps:
    - uses: actions/checkout@v4      
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Build docs
      run: |
        wget https://github.com/RascalSoftware/RAT/releases/download/nightly/Linux.zip
        unzip Linux.zip -d API/
        python -m pip install --upgrade pip
        pip install matlabengine==24.1.*
        pip install -r requirements.txt
        python build_docs.py
    - name: Checkout gh-pages
      if: github.ref == 'refs/heads/main'
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: _web
    - name: Deploy docs locally
      if: github.ref == 'refs/heads/main'
      run: |
        python deploy.py
        cd _web
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Publish Documentation" || true
        git push
