name: Build Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: Linux

    steps:
    - uses: actions/checkout@v4      
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download MATLAB RAT
      run: |
        wget https://github.com/RascalSoftware/RAT/releases/download/nightly/Linux.zip
        unzip Linux.zip -d API/
    - name: Build docs
      run: |
        url="https://rascalsoftware.github.io/RAT-Docs/"
        echo -n ${url} > source/url.txt
        python build_docs.py
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Checkout gh-pages
      if: github.ref == 'refs/heads/main'
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: _web
    - name: Deploy Docs
      if: github.ref == 'refs/heads/main'
      run: |
        python deploy.py ${{github.ref}}
        cd _web
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Publish Documentation" || true
        git push
      
