name: Buld Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4      
      with:
        submodules: true
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: _web
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
    - name: Set up Python 
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download MATLAB RAT
      run: |
        wget https://github.com/RascalSoftware/RAT/releases/download/nightly/Linux.zip
        unzip Linux.zip -d API/
    - name: Build docs
      run: python build_docs.py
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: _web
    - name: Build and Deploy Docs
      run: |
        make html
        python deploy.py ${{github.ref}}
        cd _web
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Publish Documentation" || true
        git push
